### ISSUE TITLE
Crear clases necesarias para el proyecto

### ISSUE THREAD

**Issue by cheesecodestudio** [cheesecodestudio/debts-manager#11]
# Descripción

Crear las siguientes clases: Esta pendiente a definir por @Ejduran

Nombre clase
- atributos - tipo
- Color - texto: Ejemplo, `#FFFFFF`
- Cantidad - número: Ejemplo, 10

**Comment by cheesecodestudio** [comment]
@Ejduran
Recuerde actualizar la tarea con el nombre del atributo y el tipo de dato que es: si es texto, numero, lista, etc.

**Comment by Ejduran** [comment]
```
class Dinero():
  incomes=0
  expenses=0
  balance=0
  movements=[Movimiento]

class Movements:
  type=("ingreso"/"gasto")
  amoun=0
  typeMovement="comida","transporte","estudio","ahorro","otros"
```

Nuestro objeto principal va a ser el siguiente:

`money=Money(0,0,0,[])`
